/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Banner: typeof import('./src/components/Banner.vue')['default']
    BeneficiosSection: typeof import('./src/components/BeneficiosSection.vue')['default']
    ContatoSection: typeof import('./src/components/ContatoSection.vue')['default']
    MainFooter: typeof import('./src/components/MainFooter.vue')['default']
    MainHeader: typeof import('./src/components/MainHeader.vue')['default']
    ProjetosSection: typeof import('./src/components/ProjetosSection.vue')['default']
    ServicoSection: typeof import('./src/components/ServicoSection.vue')['default']
  }
}
